export const database = [
    // Pelúcias
    {
        codigoProduto: 1,
        tituloProduto: "Sanrio Hello Kitty \"Boa Noite\"",
        preco: 150.00,
        descricao: "Sanrio Hello Kitty \"Boa Noite\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "promocoes",
        exibirHome: true
    },
    {
        codigoProduto: 2,
        tituloProduto: "Sanrio Pochacco luminária\"",
        preco: 60.00,
        descricao: "Sanrio Pochacco luminária\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "promocoes",
        exibirHome: true
    },
    {
        codigoProduto: 3,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "promocoes",
        exibirHome: true
    },
    {
        codigoProduto: 4,
        tituloProduto: "Sanrio Hello Kitty \"Boa Noite\"",
        preco: 150.00,
        descricao: "Sanrio Hello Kitty \"Boa Noite\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: true
    },
    {
        codigoProduto: 5,
        tituloProduto: "Sanrio Pochacco luminária\"",
        preco: 60.00,
        descricao: "Sanrio Pochacco luminária\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "novidades",
        exibirHome: true
    },
    {
        codigoProduto: 6,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "novidades",
        exibirHome: true
    },
    {
        codigoProduto: 7,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "novidades",
        exibirHome: true,
    },
    {
        codigoProduto: 8,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    // Colecionáveis
    {
        codigoProduto: 9,
        tituloProduto: "Sanrio Hello Kitty \"Boa Noite\"",
        preco: 150.00,
        descricao: "Sanrio Hello Kitty \"Boa Noite\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 10,
        tituloProduto: "Sanrio Pochacco luminária\"",
        preco: 60.00,
        descricao: "Sanrio Pochacco luminária\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 11,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 12,
        tituloProduto: "Sanrio Hello Kitty \"Boa Noite\"",
        preco: 150.00,
        descricao: "Sanrio Hello Kitty \"Boa Noite\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 13,
        tituloProduto: "Sanrio Pochacco luminária\"",
        preco: 60.00,
        descricao: "Sanrio Pochacco luminária\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 14,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 15,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 16,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    // LEGO
    {
        codigoProduto: 17,
        tituloProduto: "Sanrio Hello Kitty \"Boa Noite\"",
        preco: 150.00,
        descricao: "Sanrio Hello Kitty \"Boa Noite\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/cinnamonroll - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 18,
        tituloProduto: "Sanrio Pochacco luminária\"",
        preco: 60.00,
        descricao: "Sanrio Pochacco luminária\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/cinnamonrollFRUTAS - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 19,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/coloridoSanrio - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 20,
        tituloProduto: "Sanrio Hello Kitty \"Boa Noite\"",
        preco: 150.00,
        descricao: "Sanrio Hello Kitty \"Boa Noite\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/myM - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 21,
        tituloProduto: "Sanrio Pochacco luminária\"",
        preco: 60.00,
        descricao: "Sanrio Pochacco luminária\"",
        imagemProduto: {
            img1: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/myMK -PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 22,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/pompompurin - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 23,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/sanrioMesmacor - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    },
    {
        codigoProduto: 24,
        tituloProduto: "Sanrio Lancheira Hello Kitty",
        preco: 30.00,
        descricao: "Sanrio Lancheira Hello Kitty",
        imagemProduto: {
            img1: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
            img2: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
            img3: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
            img4: "./images/PELÚCIAS/sanrioCUTE - PRINCIPAL.jfif",
        },
        categoriaProduto: "Brinquedos",
        classificacaoProduto: "Mais_Vendidos",
        exibirHome: false,
    }
];